language: nix

cache:
  directories:
    - $HOME/.stack

before_install:
  - nix-env -i stack
  - stack --nix install hscolour

script:
  - stack --nix --no-terminal test

notifications:
  email: false
