sudo: true

cache:
  directories:
    - $HOME/.stack

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - sudo apt-get install haskell-stack libcairo2-dev libglib2.0-dev libgtk-3-dev libpango1.0-dev libx11-dev libxext-dev libxrandr-dev x11proto-core-dev zlib1g-dev
  - stack --no-terminal upgrade
  - stack --no-terminal setup
  - stack --no-terminal install hscolour

script:
  - stack --no-terminal --skip-ghc-check test

notifications:
  email: false
