resolver: lts-9.0

packages:
  - accumulate
  - acme-truthy
  - alternating-characters
  - atomic-modify
  - bad-twenty-four
  - data-forest
  - decimal-text
  - elephant
  - encodings
  - equivalent
  - exception-records
  - exponent-dag
  - gadt-constraint-record-example
  - human-parse
  - human-text
  - irs-forms
  - list-monoids
  - mvar-lock
  - non-threaded-fork-failure
  - num-qq
  - partial-ord
  - power-of-two
  - tchan-log-demo

extra-deps:
  - hedgehog-0.5

nix:
  packages:
    - zlib
