resolver: lts-8.23

packages:
  - accumulate
  - acme-truthy
  - alternating-characters
  - atomic-modify
  - clock-app
  - data-forest
  - decimal-text
  - elephant
  - encodings
  - exception-records
  - fizzbuzz-as-a-service
  - gadt-constraint-record-example
  - human-parse
  - human-text
  - irs-forms
  - loc
  - loc-test
  - list-monoids
  - mvar-lock
  - non-threaded-fork-failure
  - num-qq
  - partial-ord
  - power-of-two
  - tchan-log-demo

extra-deps:
  - hedgehog-0.5
  - X11-extras-0.4

nix:
  shell-file: shell.nix
