resolver: lts-8.8

packages:
  - accumulate
  - atomic-modify
  - clock-app
  - data-forest
  - decimal-text
  - elephant
  - encodings
  - exception-records
  - human-parse
  - human-text
  - irs-forms
  - loc
  - loc/test
  - list-monoids
  - mvar-lock
  - num-qq
  - tchan-log-demo

extra-deps:
  - hedgehog-0.2.2
  - X11-extras-0.4

nix:
  shell-file: shell.nix
