name: fizzbuzz-as-a-service
version: 0.1.0.0
category: Network APIs

synopsis:    FizzBuzz as a service.
description: FizzBuzz as a service.

author:     Chris Martin <ch.martin@gmail.com>
maintainer: Chris Martin <ch.martin@gmail.com>

homepage: https://github.com/chris-martin/haskell-libraries

license:      Apache-2.0
license-file: license.txt

default-extensions:
  - NoImplicitPrelude

executables:
  fizzbuzz-server:
    source-dirs: app
    main: fizzbuzz-server.hs
    ghc-options:
      - -Wall
      - -threaded
    dependencies:
      - async
      - base >= 4.9 && < 4.10
      - bytestring
      - network-simple
      - optparse-applicative
