name: loc
version: 0.1.2.1
category: Data Structures

synopsis: |
  Types representing line and column positions and ranges in text files.

description: |
  The package name /loc/ stands for “location” and is also an allusion to the
  acronym for “lines of code”.

  The @Loc@ type represents a caret position in a text file, the @Span@ type
  is a nonempty range between two @Loc@s, and the @Area@ type is a set of
  non-touching @Span@s.

library:
  source-dirs: src
  exposed-modules:
    - Data.Loc
    - Data.Loc.Area
    - Data.Loc.Exception
    - Data.Loc.Internal.Map
    - Data.Loc.Internal.Prelude
    - Data.Loc.List.OneToTwo
    - Data.Loc.List.ZeroToTwo
    - Data.Loc.Loc
    - Data.Loc.Pos
    - Data.Loc.Span
    - Data.Loc.Types

author:     Chris Martin <ch.martin@gmail.com>
maintainer: Chris Martin <ch.martin@gmail.com>

homepage: https://github.com/chris-martin/haskell-libraries

license:      Apache-2.0
license-file: license.txt

dependencies:
  - base >= 4.9 && < 4.10
  - containers

ghc-options:
  - -Wall

default-extensions:
  - NoImplicitPrelude

tests:
  doctest:
    source-dirs: test
    main: doctest.hs
    dependencies:
      - doctest
      - loc
    ghc-options:
      - -threaded
  hedgehog:
    source-dirs: test
    main: hedgehog.hs
    dependencies:
      - hedgehog
      - loc
      - loc-test
    ghc-options:
      - -threaded

extra-source-files:
  - README.md
  - example.svg
  - example.png
